spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1:8b        # default model (editor neće prijavljivati grešku)
          temperature: 0.1
          top-p: 0.9
          num-predict: 1500
          repeat-penalty: 1.1
      models:
        gemma:
          model: gemma3:4b-it-qat
          temperature: 0.1
          top-p: 0.85
          num-predict: 1000
          repeat-penalty: 1.05
        llama:
          model: llama3.1:8b
          temperature: 0.1
          top-p: 0.9
          num-predict: 1500
          repeat-penalty: 1.1

      embedding:
        model: nomic-embed-text
        options:
          truncate: true

    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768

  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: ${DB_USERNAME:testuser}
    password: ${DB_PASSWORD:testpwd}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: false

# Logging
logging:
  level:
    dev.markos3d.spring_ai: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.ai.vectorstore: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
