spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
          temperature: 0.1          # manje kreativnosti za preciznije odgovore
          top-p: 0.9
          num-predict: 1500        # max tokens za odgovor
          repeat-penalty: 1.1      # izbegava ponavljanje
      embedding:
        model: nomic-embed-text
        options:
          truncate: true
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768

  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: ${DB_USERNAME:testuser}
    password: ${DB_PASSWORD:testpwd}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: false

# Custom properties
app:
  rag:
    ingestion:
      enabled: true
      skip-if-exists: true
    alternative-splitter:
      enabled: false

# Logging
logging:
  level:
    dev.markos3d.spring_ai: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.ai.vectorstore: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  